version: '3.8'

services:
  app:
    # Use the pre-built image from the registry, tagged by the CI pipeline
    # The IMAGE_TAG variable should be set in the environment by the deploy script
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-${GITHUB_REPOSITORY}}:${IMAGE_TAG:-latest}
    ports:
      # Map host port (defined by APP_HOST_PORT env var) to container port 3000
      - "${APP_HOST_PORT:-3000}:3000" # Default to 3000 if var not set
    environment:
      # Use Docker Compose variable substitution to get values from environment/.env
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: ${DATABASE_URL} # Ensure this points to HOST DB in .env
      JWT_SECRET: ${JWT_SECRET}
      BLOCKFROST_API_KEY: ${BLOCKFROST_API_KEY}
      BLOCKFROST_NETWORK: ${BLOCKFROST_NETWORK}
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    # Optional: Uncomment to explicitly load the .env file created by CI
    # env_file:
    #  - .env
